/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/app/': RouteRecordInfo<'/app/', '/app', Record<never, never>, Record<never, never>>,
    '/app/assignments/': RouteRecordInfo<'/app/assignments/', '/app/assignments', Record<never, never>, Record<never, never>>,
    '/app/delegates/': RouteRecordInfo<'/app/delegates/', '/app/delegates', Record<never, never>, Record<never, never>>,
    '/app/drops/': RouteRecordInfo<'/app/drops/', '/app/drops', Record<never, never>, Record<never, never>>,
    '/app/external/': RouteRecordInfo<'/app/external/', '/app/external', Record<never, never>, Record<never, never>>,
    '/app/notifications/': RouteRecordInfo<'/app/notifications/', '/app/notifications', Record<never, never>, Record<never, never>>,
    '/app/permissions/': RouteRecordInfo<'/app/permissions/', '/app/permissions', Record<never, never>, Record<never, never>>,
    '/app/settings/': RouteRecordInfo<'/app/settings/', '/app/settings', Record<never, never>, Record<never, never>>,
  }
}
